### PR TITLE
Case insensitive user emails

### LINKED ISSUE #470: Login - emails are case sensitive
Resolved by #749, after scrutiny. Requires removing dupes on the live site ahead of deployment.

# Description
Emails are saved as case-sensitive. You must therefore use the same to log in as when you registered. However, they should be case-insensitive.

# Steps to Reproduce
1. register using an all lowercase email
2. attempt to log in using the same email but with uppercase letters.

### PR DESCRIPTION
**Pull request by gggrant**
Resolves #470

Adds a Postgres package for citext (case insensitive text) field and alters the email column on users table.

Do not merge until existing duplicates have been removed on the live site.

### CODE REVIEW

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 48  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 57.99999999999999  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by vid** [comment]
Unless they are related, package upgrades should be in a separate PR. 
Are there any reasonable integration tests to add for this?

**Comment by xander-miller** [comment]
531b797 Adds a feature test of login email case insensitivity. The test is currently failing. I believe the test is correct and login emails are still case sensitive.

**Comment by gggrant** [comment]
@xander-miller the test is useful but doesn't seem to reflect the application behaviour (at least for me). Maybe the extension isn't being added when refreshing the database for tests? Worth some more investigation. Any ideas welcome/appreciated.

**Pull request merged**
