### PR TITLE
Review Applications

### PR DESCRIPTION
**Pull request by tristan-orourke**
UI is built using a react component written in typescript.

Pull request to resolve issue #687

# Description
This is an incremental step towards implementing the final design, but for this interim build we will be using the following wire-frame as a basis:
https://xd.adobe.com/view/100bf2e1-1ebd-4b31-77bf-fdcf162b7393-663a/

We are also building off of the existing manager dashboard, which lists candidates for all the manager's job posters.

The goal of this story is to add rudimentary sorting for applicants, simplify the fields displayed and improve the visual design of the "screening info". This will get us most of the way towards having something we can share with Hiring Managers currently using Talent Cloud.

Note, the candidate "screening info" view is currently displayed on both the "My Job Posters" page and at the top of the candidates Application page (when managers are looking at a candidates application).  That duplication of the display is still desirable.

### Full page
- [ ] This page should fall under "My Job Posters" link in the menu. @gobyrne is happy to be overruled on this
- [x] Job Title used as header
- [x] Number of days since poster closed displayed at top of page
- [x] Like the wire frame, there should be overarching categories that candidates are displayed in but they should be titled "Under Consideration" (at the top), "Optional Consideration" (in the middle), and "No Longer under consideration" (on the bottom).
- [ ] As in the wire frame "Under Consideration"should be split into "Step 1" and "Step 2".
- [ ] As a placeholder for priorities, "Step 1" should simply display the text: "Contact Talent Cloud to get a list of priorities that applied to this position. They must be reviewed and considered first." (We will make priorities functional in the future, see #690 and #691)
- [x] As it is displayed on the wireframes, dropdown categories should be maintained in the following order:

     Under Consideration:
          - Step 1: Priority Applications
          - Step 2: Veterans and Canadian citizens

     Optional Consideration:
          - Optional 1: Non-Canadian Citizens
          - Optional 2: Do not meet essential criteria

     No longer under consideration:
          - Priority Applications
          - Veterans and Canadian citizens
          - Non-Canadian Citizens
          - Do not meet essential criteria

- [x] These subcategories are only visible if there is at least 1 candidate in them (as it is currently implemented)

### Screening info (a combination of the images below)
- [x] Name and email on the left
- [x] Link to existing candidate applications page
- [x] Link to existing candidate profile page
- [x] Re-purpose the existing "Reviewed" select input. Rename it to: "Status". Drop down options are: "Still In" (green), "Not Reviewed" (yellow), "Still Thinking" (orange) and "Screened Out" (Uncolored, or Red if it's better). If you need to migrate database values, set all "Yes" to "Still In", "Partially" values to "Still Thinking" and "No" to "Screened Out".
- [x] The colors refer to the corresponding icon displayed on the left
- [x] Veterans should also get an icon and the label "veteran" on the left. (we will add similar for priorities in the future)
- [x] Status of all candidates (including "other" or "non-citizens") is "Not Reviewed" by default.
- [x] If possible, "Not Reviewed" should no longer be an option once something else has been picked.
- [x] "Add Note" button opens up a modal with a text box, save button and delete note button (Gray is a little worried this makes it too easy to delete notes).
- [x] Do not include the "Decision" or "Reviewer" inputs from the old dashboard. If you need to migrate database values, concatenate the values of "Decision", "Reviewer" and "Notes" and save it all as "Notes".
- [x] Save button - Saves values for this candidate. If saving will change the overarching category that the candidate is in (see sorting below), then a dialogue box appears asking for confirmation that the user wants to "Screen out the candidate" or "Screen the candidate back in". (copy improvements welcome)
- [ ] All of this should look and function the same from the view at the top of the candidate's Application page as well.

### Sorting
- [x] Veterans and Canadian citizens should start in the "Under Consideration (step 2)" section by default.
- [x] "Non-citizens" or "Do not meet essential criteria" should start in a corresponding subcategory the "Optional Consideration" section (as in wireframe)
- [x] Saving the status "Screened out" moves a candidate to the "No longer under consideration" section (with modal dialogue confirmation) if they are not already there.
- [x] Saving a status other than "Screened out" moves a candidate to their previous section (again using a dialogue box), whether that was "Under Consideration (step 2)" section or "Optional Consideration" if they are not already there.
- [x] Within the subsections of "Under Consideration (step 2 for now)" AND the subsections of "Optional Consideration" candidates should be sorted by status: "Still In" (top & green), "Not Reviewed" (middle & yellow), "Still Thinking" (bottom & orange)
- [x] Veterans should be sorted to the top of each status group when in "Under Consideration (step 2)" and at the top of all other subsections.

# Images
Current display of candidates on manager dashboard. AKA "screening info"
image

Updated display of candidate
screen shot 2019-02-07 at 1 34 05 pm

### CODE REVIEW

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 45  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 57.99999999999999  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 45  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 59  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 45  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 59  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 44  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 60  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 46  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 56.99999999999999  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by tristan-orourke** [comment]
This is working, and almost all of the acceptance criteria are fulfilled. The "Screen Out All Optional Candidates" button isn't functional yet, the styling is wrong on the application view (eg https://talent.local.ca/en/manager/applications/1) and none of the text is localized yet.

This definitely requires running `npm install` and `npm run dev`, with all the work in javascript.

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 44  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 59  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 47  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 56.99999999999999  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Pull request merged**
