### PR TITLE
Adds default options to Select elements

### PR DESCRIPTION
**Pull request by JoshBeveridge**
Issue #603 
@Khristophor do you mind taking a look at this? Basically if you submit a form with a new default option selected, I'm receiving a Laravel error. @gggrant , do you mind taking a look at the solution I've implemented to see if it helps solve the accessibility issue? @gobyrne There are translations required for these new lang variables as well. You can find the files I've edited in the PR diff. Some of the manager side `select` elements didn't have translation files yet, so while they do need to be translated, there's no spot for them yet.

### CODE REVIEW

**Review by gggrant — CHANGES_REQUESTED** [review]
The default option in dropdowns look good.

Can we use consistent language? i.e. Either always or never use "please".

**Comment by joshdrink** [comment]
@gggrant Changed.

**Review by gggrant — COMMENTED** [review]
Changes completed.

Leaving the PR in this state until we have translations for the new text.

**Review by gggrant — APPROVED** [review]

**Review by gggrant — CHANGES_REQUESTED** [review]
Didn't mean to approbve until required elements are sorted out.

**Comment by gobyrne** [comment]
This pull request addresses #603

**Comment by xander-miller** [comment]
Resolves #603

**Comment by gggrant** [comment]
## Lighthouse report for the URL: **http://localhost:8000/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 48  | 0  |  ✅  |
| pwa  | 27  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 80  | 0  |  ✅  |
| seo  | 80  | 0  |  ✅  |

</details>
    
## Lighthouse report for the URL: **https://talent.canada.ca/en**
<details opened=false>
<summary>Click here to open results 📉</summary>

| Category   | Score | Threshold  | Pass |
| ------------- | ------------- | ------------- | ------------- |
| performance  | 61  | 0  |  ✅  |
| pwa  | 54  | 0  |  ✅  |
| accessibility  | 100  | 100  |  ✅  |
| best-practices  | 73  | 0  |  ✅  |
| seo  | 90  | 0  |  ✅  |

</details>

**Comment by Khristophor** [comment]
@gobyrne translations required in `resources/lang/fr/validation.php`, you can see the English versions in my most recent commit. @gggrant feel free to modify the English versions to whatever makes the most sense for UI/accessibility.

**Review by gggrant — APPROVED** [review]

**Review by gggrant — CHANGES_REQUESTED** [review]
Compare front-end form validation on applicant profiles pages: Work Samples (better) and References (worse). Any idea why the error messages are blocked on one and not the other?

@joshdrink ?

**Comment by gggrant** [comment]
Opening another, cleaner PR for this issue.

**Pull request closed without merging**
