### PR TITLE
Feature/form error css

### PR DESCRIPTION
**Pull request by yonikid15**
All finished, ready for review/testing.  resolves issue #766

### CODE REVIEW

**Comment by yonikid15** [comment]
kk Ill check it out now and let you know

**Comment by gggrant** [comment]
I'd prefer one `auth-alert` class for the whole list. There's some areas where this styling could produce a comically long list of errors.

@gobyrne any opinion? See below.

screen shot 2019-03-08 at 8 06 19 am

**Comment by gobyrne** [comment]
Agree with @gggrant. 1 box for whole list is better

**Comment by gggrant** [comment]
Looks good. Resolves #766

**Pull request merged**
